version: "3"

tasks:

  install:
    cmds:
      - poetry install

  install:
    cmds:
      - ruff format .

  setup:
    cmds:
      - dbt deps
      - dbt seed
      - rm -rf jaffle-data
      - dbt run
      - dbt test
